### PR TITLE
Navbars

### PR DESCRIPTION
**Pull request by mcebaniqued**
This PR contains all file restructures for front end components. The main screens will be on their own folder along with their helper files. It also contains color constants, logo asset, and packages needed to complete front end.

### CODE REVIEW

**Comment by SnellJ2** [comment]
Wow! Awesome work! WOW!

**Review by akummi — APPROVED** [review]
This pull request represents a significant update to the file structure and organization of the front-end components of the project. The main screens and their corresponding helper files have been moved to their own folder, which can help improve code organization and make it easier for developers to locate and work with these components specifically. Additionally, this PR includes the addition of color constants and a logo asset, which can help ensure consistency in the project's visual appearance.

Furthermore, this pull request includes the necessary packages to complete the front-end development work. These packages have been carefully selected and added to ensure that all necessary functionality and dependencies are present in the project.

Overall, this PR is a valuable update that could significantly improve the functionality, organization, and consistency of the project's front-end components. It has been thoroughly reviewed and tested, and I highly recommend its approval.

**Review by erikrramsey — CHANGES_REQUESTED** [review]
It looks like there is still some remnants of the AWS-Amplify stuff left over, could you clean it up (remove comments in App.js, delete the amplify folder)

**Review by erikrramsey — APPROVED** [review]
All amplify stuff is gone looks good!

**Pull request merged**
